export const GET_VIDEOGAMES = 'GET_VIDEOGAMES'
export const GET_VIDEOGAME_DETAIL = 'GET_VIDEOGAME_DETAIL'
export const GET_GENRES = 'GET_GENRES'
export const GET_VIDEOGAMES_NAMES = 'GET_VIDEOGAMES_NAME'
export const GET_PLATFORMS = 'GET_PLATFORMS'
export const CREATE_VIDEOGAME = "CREATE_VIDEOGAME"
export const CREATED_FILTER = 'CREATED_FILTER'
export const ORDER_BY_NAME = "ORDER_BY_NAME"
export const ORDER_BY_RATING  = 'ORDER_BY_RATING'
export const FILTER_BY_GENRES = "FILTER_BY_GENRES"
export const CLEAN_DETAIL = "CLEAN_DETAIL"
export const CLEAN_FILTERS = 'CLEAN_FILTERS'
export const CLEAN_VIDEOGAMES = 'CLEAN_VIDEOGAMES'

export const UPDATE_FILTERS = "UPDATE_FILTERS"
